const dataSource = [
  {
    name: "Ana Maria Silva",
    cns: "123456789012345",
    birthDate: "1985-05-14",
    gender: "Feminino",
    pregnancyStage: "Primeiro trimestre",
    race: "Branco",
    educationLevel: "Superior Completo",
    motherName: "Maria Silva",
  },
  {
    name: "Carlos Eduardo Oliveira",
    cns: "234567890123456",
    birthDate: "1990-07-23",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Pardo",
    educationLevel: "Médio Completo",
    motherName: "Ana Oliveira",
  },
  {
    name: "Fernanda Santos",
    cns: "345678901234567",
    birthDate: "1992-12-10",
    gender: "Feminino",
    pregnancyStage: "Segundo trimestre",
    race: "Preto",
    educationLevel: "Superior Incompleto",
    motherName: "Joana Santos",
  },
  {
    name: "João Pedro Costa",
    cns: "456789012345678",
    birthDate: "1988-03-30",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Branco",
    educationLevel: "Fundamental Completo",
    motherName: "Mariana Costa",
  },
  {
    name: "Mariana Oliveira",
    cns: "567890123456789",
    birthDate: "1995-11-02",
    gender: "Feminino",
    pregnancyStage: "Terceiro trimestre",
    race: "Amarelo",
    educationLevel: "Médio Completo",
    motherName: "Sofia Oliveira",
  },
  {
    name: "Bruno Lima",
    cns: "678901234567890",
    birthDate: "1982-04-15",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Indígena",
    educationLevel: "Fundamental Incompleto",
    motherName: "Clara Lima",
  },
  {
    name: "Camila Souza",
    cns: "789012345678901",
    birthDate: "1991-06-18",
    gender: "Feminino",
    pregnancyStage: "Primeiro trimestre",
    race: "Pardo",
    educationLevel: "Superior Completo",
    motherName: "Regina Souza",
  },
  {
    name: "Lucas Fernandes",
    cns: "890123456789012",
    birthDate: "1987-09-12",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Preto",
    educationLevel: "Médio Incompleto",
    motherName: "Lúcia Fernandes",
  },
  {
    name: "Patrícia Rocha",
    cns: "901234567890123",
    birthDate: "1994-02-08",
    gender: "Feminino",
    pregnancyStage: "Segundo trimestre",
    race: "Branco",
    educationLevel: "Superior Incompleto",
    motherName: "Helena Rocha",
  },
  {
    name: "Ricardo Alves",
    cns: "012345678901234",
    birthDate: "1989-10-22",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Amarelo",
    educationLevel: "Fundamental Completo",
    motherName: "Isabel Alves",
  },
  {
    name: "Larissa Mendes",
    cns: "123450987654321",
    birthDate: "1996-05-05",
    gender: "Feminino",
    pregnancyStage: "Terceiro trimestre",
    race: "Indígena",
    educationLevel: "Médio Completo",
    motherName: "Adriana Mendes",
  },
  {
    name: "Eduardo Pereira",
    cns: "234560876543210",
    birthDate: "1984-08-30",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Pardo",
    educationLevel: "Superior Completo",
    motherName: "Márcia Pereira",
  },
  {
    name: "Isabela Gonçalves",
    cns: "345670765432109",
    birthDate: "1993-12-25",
    gender: "Feminino",
    pregnancyStage: "Primeiro trimestre",
    race: "Preto",
    educationLevel: "Superior Incompleto",
    motherName: "Tatiana Gonçalves",
  },
  {
    name: "Renato Ribeiro",
    cns: "456780654321098",
    birthDate: "1986-01-11",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Branco",
    educationLevel: "Médio Completo",
    motherName: "Rosana Ribeiro",
  },
  {
    name: "Juliana Martins",
    cns: "567890543210987",
    birthDate: "1992-07-27",
    gender: "Feminino",
    pregnancyStage: "Segundo trimestre",
    race: "Amarelo",
    educationLevel: "Fundamental Completo",
    motherName: "Silvana Martins",
  },
  {
    name: "Pedro Gomes",
    cns: "678900432109876",
    birthDate: "1985-03-21",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Indígena",
    educationLevel: "Fundamental Incompleto",
    motherName: "Vera Gomes",
  },
  {
    name: "Aline Barros",
    cns: "789010321098765",
    birthDate: "1990-09-18",
    gender: "Feminino",
    pregnancyStage: "Terceiro trimestre",
    race: "Pardo",
    educationLevel: "Médio Incompleto",
    motherName: "Cristina Barros",
  },
  {
    name: "Felipe Azevedo",
    cns: "890120210987654",
    birthDate: "1983-11-07",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Preto",
    educationLevel: "Superior Completo",
    motherName: "Débora Azevedo",
  },
  {
    name: "Sofia Carvalho",
    cns: "901230109876543",
    birthDate: "1995-01-03",
    gender: "Feminino",
    pregnancyStage: "Primeiro trimestre",
    race: "Branco",
    educationLevel: "Superior Incompleto",
    motherName: "Fátima Carvalho",
  },
  {
    name: "Gustavo Silva",
    cns: "012340987654321",
    birthDate: "1988-06-29",
    gender: "Masculino",
    pregnancyStage: "N/A",
    race: "Amarelo",
    educationLevel: "Médio Completo",
    motherName: "Renata Silva",
  },
];

export default dataSource;
