const dataSource = [
    {
      medical_record: "12345",
      patient_name: "João Silva",
      entry_type: "Consulta",
      special_population: "Nenhum",
      is_government_beneficiary: "Sim",
      form: "Formulário 1",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Negativo",
      health_unit: "Unidade A",
    },
    {
      medical_record: "67890",
      patient_name: "Maria Souza",
      entry_type: "Exame",
      special_population: "Gestante",
      is_government_beneficiary: "Não",
      form: "Formulário 2",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Positivo",
      health_unit: "Unidade B",
    },
    {
      medical_record: "11223",
      patient_name: "Carlos Oliveira",
      entry_type: "Internação",
      special_population: "Idoso",
      is_government_beneficiary: "Sim",
      form: "Formulário 3",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Positivo",
      health_unit: "Unidade C",
    },
    {
      medical_record: "33445",
      patient_name: "Ana Pereira",
      entry_type: "Consulta",
      special_population: "Nenhum",
      is_government_beneficiary: "Não",
      form: "Formulário 4",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Negativo",
      health_unit: "Unidade D",
    },
    {
      medical_record: "55667",
      patient_name: "Lucas Martins",
      entry_type: "Exame",
      special_population: "Criança",
      is_government_beneficiary: "Sim",
      form: "Formulário 5",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Negativo",
      health_unit: "Unidade E",
    },
    {
      medical_record: "77889",
      patient_name: "Juliana Costa",
      entry_type: "Internação",
      special_population: "Gestante",
      is_government_beneficiary: "Não",
      form: "Formulário 6",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Positivo",
      health_unit: "Unidade F",
    },
    {
      medical_record: "99001",
      patient_name: "Paulo Fernandes",
      entry_type: "Consulta",
      special_population: "Nenhum",
      is_government_beneficiary: "Sim",
      form: "Formulário 7",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Positivo",
      health_unit: "Unidade G",
    },
    {
      medical_record: "11212",
      patient_name: "Fernanda Lima",
      entry_type: "Exame",
      special_population: "Idoso",
      is_government_beneficiary: "Não",
      form: "Formulário 8",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Negativo",
      health_unit: "Unidade H",
    },
    {
      medical_record: "22334",
      patient_name: "Bruno Alves",
      entry_type: "Internação",
      special_population: "Criança",
      is_government_beneficiary: "Sim",
      form: "Formulário 9",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Positivo",
      health_unit: "Unidade I",
    },
    {
      medical_record: "44556",
      patient_name: "Clara Santos",
      entry_type: "Consulta",
      special_population: "Nenhum",
      is_government_beneficiary: "Não",
      form: "Formulário 10",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Negativo",
      health_unit: "Unidade J",
    },
    {
      medical_record: "66778",
      patient_name: "Mariana Lima",
      entry_type: "Exame",
      special_population: "Gestante",
      is_government_beneficiary: "Sim",
      form: "Formulário 11",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Negativo",
      health_unit: "Unidade K",
    },
    {
      medical_record: "88990",
      patient_name: "Ricardo Martins",
      entry_type: "Internação",
      special_population: "Idoso",
      is_government_beneficiary: "Não",
      form: "Formulário 12",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Positivo",
      health_unit: "Unidade L",
    },
    {
      medical_record: "10112",
      patient_name: "Beatriz Souza",
      entry_type: "Consulta",
      special_population: "Nenhum",
      is_government_beneficiary: "Sim",
      form: "Formulário 13",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Positivo",
      health_unit: "Unidade M",
    },
    {
      medical_record: "13141",
      patient_name: "Felipe Costa",
      entry_type: "Exame",
      special_population: "Nenhum",
      is_government_beneficiary: "Não",
      form: "Formulário 14",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Negativo",
      health_unit: "Unidade N",
    },
    {
      medical_record: "15161",
      patient_name: "Isabela Ribeiro",
      entry_type: "Internação",
      special_population: "Gestante",
      is_government_beneficiary: "Sim",
      form: "Formulário 15",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Negativo",
      health_unit: "Unidade O",
    },
    {
      medical_record: "17181",
      patient_name: "Eduardo Ferreira",
      entry_type: "Consulta",
      special_population: "Idoso",
      is_government_beneficiary: "Não",
      form: "Formulário 16",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Positivo",
      health_unit: "Unidade P",
    },
    {
      medical_record: "19202",
      patient_name: "Camila Gomes",
      entry_type: "Exame",
      special_population: "Nenhum",
      is_government_beneficiary: "Sim",
      form: "Formulário 17",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Positivo",
      health_unit: "Unidade Q",
    },
    {
      medical_record: "21222",
      patient_name: "Rafael Rodrigues",
      entry_type: "Internação",
      special_population: "Criança",
      is_government_beneficiary: "Não",
      form: "Formulário 18",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Negativo",
      health_unit: "Unidade R",
    },
    {
      medical_record: "23242",
      patient_name: "Larissa Azevedo",
      entry_type: "Consulta",
      special_population: "Gestante",
      is_government_beneficiary: "Sim",
      form: "Formulário 19",
      extra_pulmonary_type: "Nenhum",
      diagnosis: "Positivo",
      culture: "Negativo",
      health_unit: "Unidade S",
    },
    {
      medical_record: "25252",
      patient_name: "Gustavo Alves",
      entry_type: "Exame",
      special_population: "Nenhum",
      is_government_beneficiary: "Não",
      form: "Formulário 20",
      extra_pulmonary_type: "Pulmonar",
      diagnosis: "Negativo",
      culture: "Positivo",
      health_unit: "Unidade T",
    },
  ];
  
  export default dataSource;
  